### ISSUE TITLE
Rank is empty on text with repeated sentences

### ISSUE THREAD

**Issue by slavablind91** [JesusIslam/tldr#10]
Try to summarize next text
`bag.Summarize("Hello, world. Hello, world. Hello, world.", 1)`
and got error
`Ranks is empty`

I think the summarize function need return `Hello, world.`
Why this happens?

**Comment by slavablind91** [comment]
The problem is weight for each Edge become 0.
For identical vectors i think need weight=1

**Comment by JesusIslam** [comment]
@slavablind91  OK, I just started working on this again.
I just realized that if you have the same sentences, it would make the edges weight to 0 because there is literally no difference between them. This is an expected behavior in weighing phase. 

So if you have empty ranks, it means you can pick whatever sentences you wanted because they don't matter. I will change this to not return error because this shouldn't be an error.
